import { CasesDashboardComponent } from "./cases/cases-dashboard.component";
import { EventsDashboardComponent } from "./events/events-dashboard.component";
import { MessagesDashboardComponent } from "./messages/messages-dashboard.component";
import { TasksDashboardComponent } from "./tasks/tasks-dashboard.component";
import { ListDashboardComponent } from "./list/list-dashboard.component";
export { DashboardService } from './dashboard.service'
//export { IJob } from './job.model'
export { DashboardRoutingModule } from './dashboard-routing.module';
export { DashboardModule } from './dashboard.module';
