export enum ObjectType {
  CompanyInformation = 1,
  Enum = 2,
  Message = 3,
  Policy = 4,
  UserGroup = 5,
  User = 6,
  Question = 7,
  Answer = 8,
  QuestionSet = 9,
  MacroField = 10,
  EmailTemplate = 11,
  Attorney = 12,

  //SLC
  Client = 14,
  EventType = 31,
  CardType = 32,
  Event = 33,
  EventVenue = 34,
  EventCard = 35,
  EventCardZone = 36,
  EventServiceProviderPortalRequest = 37,
  EventServiceProvider = 38,
  EventCardRequest = 39,
  EventVenueDate = 40,
  EventRequestDetails = 41,
  ResponsibleOrganizations = 42,
  EventRequestOthersDetail = 43,
  EventRequestClientDetail= 44,
  EventCardPrinting= 45,
  SendEventRequestEmail= 46,
  NewUser= 47,
  EventOverView = 47,

  Case = 15,
  ClientInputForm = 16,
  ExpertReport = 17,
  Auditor = 18,
  ExpertReportForm = 19,
  MedicalExpertReportForm = 20,
  ICD10 = 21,
 // CASEAuditInputForm = 22,
  AttorneyReferralForm = 23,
  DemandInputForm = 24,
  BodyPart = 22,
  FormTemplate = 0,
  CPTCode = 25,
  Clients = 26,
  Cases = 27,
  //ImpairmentRatings = 28,
  ImpairmentForm = 29,
  BodypartImparementMethod = 30,
}

export let ObjectTypeList = [
  { label: 'Company Information', value: 1, toolTip: 'Company Information' },
  { label: 'Enum', value: 2, toolTip: 'Enum' },
  { label: 'Message', value: 3, toolTip: 'Message' },
  { label: 'Policy', value: 4, toolTip: 'Policy' },
  { label: 'User Group', value: 5, toolTip: 'User Group' },
  { label: 'User', value: 6, toolTip: 'User' },
  { label: 'Question', value: 7, toolTip: 'Question' },
  { label: 'Answer', value: 8, toolTip: 'Answer' },
  { label: 'Question Set', value: 9, toolTip: 'Question Set' },
  { label: 'Macro Field', value: 10, toolTip: 'Macro Field' },
  { label: 'Email Template', value: 11, toolTip: 'Email Template' },
  //{ label: 'CASE Audit Input Form', value: 22, toolTip: 'CASE Audit Input Form'},
  { label: 'Attorney', value: 12, toolTip: 'Attorney' },
  { label: 'Client', value: 14, toolTip: 'Client' },
  { label: 'Case', value: 15, toolTip: 'Case' },
  { label: 'Client Input Form', value: 16, toolTip: 'Client Input Form' },
  { label: 'Expert Report', value: 17, toolTip: 'Expert Report' },
  { label: 'Auditor', value: 18, toolTip: 'Auditor' },
  { label: 'Expert Report Form', value: 19, toolTip: 'Expert Report Form' },
  { label: 'Medical Expert Report Form', value: 20, toolTip: 'Medical Expert Report Form' },
  { label: 'ICD10', value: 21, toolTip: 'ICD10' },
  { label: 'BodyPart', value: 22, toolTip: 'BodyPart' },
  { label: 'Attorney Referral Form', value: 23, toolTip: 'Attorney Referral Form' },
  { label: 'Demand Input Form', value: 24, toolTip: 'Demand Input Form' },
  { label: 'CPT Code', value: 25, toolTip: 'CPT Code' },
  { label: 'Clients', value: 26, toolTip: 'Clients' },
  { label: 'Cases', value: 27, toolTip: 'Cases' },
  { label: 'ImpairmentRatings', value: 28, toolTip: 'Impairment Ratings' },
  { label: 'Impairment Ratings Form', value: 29, toolTip: 'Impairment Ratings Form' },
  { label: 'Bodypart Imparement Method', value: 30, toolTip: 'Bodypart Imparement Method' },
  { label: 'Responsible Organizations', value: 42, toolTip: 'Responsible Organizations' },
];
